FROM composer AS builder

FROM php:fpm

COPY --from=builder /usr/bin/composer /usr/bin/composer
COPY . /var/www/html

RUN apt update && \
    apt install libzip-dev -y && \
    docker-php-ext-configure pdo && \
    docker-php-ext-install pdo pdo_mysql zip bcmath && \
    cp .env.example .env

RUN composer install --no-dev --optimize-autoloader